myMain.out: myMathFunc.o myStrFunc.o myMain.o
	gcc -o myMain.out myMain.o myMathFunc.o myStrFunc.o

myMain.o: myMain.c
	gcc -c myMain.c

myMathFunc.o: myMathFunc.c
	gcc -c myMathFunc.c

myStrFunc.o : myStrFunc.c
	gcc -c myStrFunc.c

